modelsTasks:
  - promptName: generate_nodes_from_prompt
    model: reasoning
    temperature: 1
    frequency_penalty: 0
  - promptName: chat_text_generation
    temperature: 1.5
    frequency_penalty: 0.2
  - promptName: action_generation
    temperature: 1.5
  - promptName: node_edition_json
    temperature: 0.1
    frequency_penalty: 0